### ISSUE TITLE
ADF001 - Establish requirements

### ISSUE THREAD

**Issue by ollyjohn** [ollyjohn/ADFitness#1]
Establish a provisional list of requirements from the client to enable initial designs

___

**TASKS**
- [ ] Meet with client, discuss goals
- [ ] Draw up initial requirements list
- [ ] Agree requirements with client
