### ISSUE TITLE
ADF002 - Initial considerations

### ISSUE THREAD

**Issue by ollyjohn** [ollyjohn/ADFitness#2]
Once requirements are agreed with client, research options in prominent aspects and elements of the application

___

**TASKS**
- [ ] Look into data storage providers
- [ ] Look into application types (native/hybrid)
- [ ] Look into libraries/frameworks available
- [ ] Agree on a technology stack to use for development
